version: '3.9'

services:
  db:
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Qwerty123
      - MYSQL_DATABASE=this_is_war
      - MYSQL_USER=tiw_admin
      - MYSQL_PASSWORD=123Qwerty